### ISSUE TITLE
Fbi building nonexistant

### ISSUE THREAD

**Issue by Thasimo1** [ESX-FRANCE/esx_fbi_job#11]
Hey! is this problem on my side?
![image](https://user-images.githubusercontent.com/23641264/82811187-75611f80-9e90-11ea-8777-7125a0275b58.png)

**Comment by keketiger** [comment]
Hi, You have to use an ipl charger to get inside.

I recommend this one: https://github.com/Bob74/bob74_ipl

**Comment by Thasimo1** [comment]
OK thx! you are awesome!

**Comment by keketiger** [comment]
You're welcome!
