### ISSUE TITLE
error "upvalue coords"

### ISSUE THREAD

**Issue by woraphat** [esx-france/esx_fbi_job#12]
error "upvalue coords"

How should I fix this?

**Comment by keketiger** [comment]
@woraphat Hi, what line are you getting this error on?

**Comment by woraphat** [comment]
I still have the same problem.

![image](https://user-images.githubusercontent.com/29332188/92362552-5a05e180-f11a-11ea-82e4-78b09a091d18.png)

![image](https://user-images.githubusercontent.com/29332188/92362587-65590d00-f11a-11ea-9133-f68d96c4a0d1.png)

**Comment by woraphat** [comment]
I tested it by reinstalling. But still encountered the same problem

For development information I am using es_extended Final v.1 and have installed
'es_extended',
'esx_billing',
'esx_identity',
'esx_license',
'esx_service'
Completely

I would like to encourage the development team. And ready to provide additional information if needed

**Comment by keketiger** [comment]
Got the 'coords' upvalue error when you want to spawn a prop?

**Comment by woraphat** [comment]
Yes

**Comment by keketiger** [comment]
Everything is working fine on my side. Are your sure do you have the final version of es_extended?

**Comment by keketiger** [comment]
Ok it's now correct I had not seen a typo. Try again and it should work fine.

**Comment by woraphat** [comment]
OK WORK
