### ISSUE TITLE
No armor

### ISSUE THREAD

**Issue by R3ALF4KT** [esx-france/esx_fbi_job#13]
I dont get any armor when i click on "bulletproof vest"  it just gives me the message: "you\'ve entered service, welcome!"

**Comment by keketiger** [comment]
Hi, this feature works fine for my part. Did you modify the script? If not, try installing the script again.

**Comment by R3ALF4KT** [comment]
Nope, was about to modify it, till i saw this issue comming up

**Comment by R3ALF4KT** [comment]
Fixed the issue it was due to i modified esx_service a bit wrong. Thanks!
