### ISSUE TITLE
esx_fbi_job script error

### ISSUE THREAD

**Issue by Looooky** [esx-france/esx_fbi_job#16]
Hey i got a problem:

I changed something in the config.lua.

Strictly speaking, I changed something on the guns and cars. I'm sure I didn't do anything wrong, but script errors still occur.
Please help.

I would be happy to receive an answer.

![Bild_2021-07-29_180443](https://user-images.githubusercontent.com/88155230/127526253-d5455866-7862-4d67-b7f7-713ad610826f.png)

![Bild_2021-07-29_180527](https://user-images.githubusercontent.com/88155230/127526357-2212731e-01d7-4923-a03a-0e32ebeeab09.png)

![Bild_2021-07-29_180555](https://user-images.githubusercontent.com/88155230/127526429-406453b7-d110-400d-8eab-7dc145940183.png)

![Bild_2021-07-29_180805](https://user-images.githubusercontent.com/88155230/127526777-bae72d4a-be6d-4c53-b74f-edf88d090695.png)

**Comment by keketiger** [comment]
Hi, in this screenshot : https://user-images.githubusercontent.com/88155230/127526429-406453b7-d110-400d-8eab-7dc145940183.png.
Remove bracket at lignes 146, 148, 150, 152.

**Comment by Looooky** [comment]
Thanks for your reply it works

**Comment by keketiger** [comment]
With pleasure, have fun.
