### ISSUE TITLE
fbi 

### ISSUE THREAD

**Issue by Leowing2** [ESX-FRANCE/esx_fbi_job#6]
hi ! My fbi Working point Nothing  Please help me 

![](https://cdn.discordapp.com/attachments/606889449694953493/636601005890600960/unknown.png)

**Comment by keketiger** [comment]
Hi, sorry for waiting, I fixed the problem. Tell me if everything works for you now.

**Comment by Leowing2** [comment]
Whether to reinstall?

**Comment by Leowing2** [comment]
New error QAQ

![image](https://user-images.githubusercontent.com/56931822/67497661-e0573780-f6b0-11e9-8ee2-536734fde470.png)

**Comment by Leowing2** [comment]
New error

![image](https://user-images.githubusercontent.com/56931822/67502683-dcc7ae80-f6b8-11e9-8328-0c7818c67975.png)

**Comment by keketiger** [comment]
The problem and normally solved.

**Comment by Leowing2** [comment]
Test now

**Comment by Leowing2** [comment]
![image](https://user-images.githubusercontent.com/56931822/67510262-261efa80-f6c7-11e9-84b9-e200b71540b6.png)

on Cloakrooms and Armories and Vehicles and BossActions and Elevator No work point

**Comment by Leowing2** [comment]
> ![圖片](https://user-images.githubusercontent.com/56931822/67510262-261efa80-f6c7-11e9-84b9-e200b71540b6.png)
> 
> 關於衣帽間，軍械庫和車輛及上司的動作和電梯無工作點

F8 on error QAQ

**Comment by keketiger** [comment]
Hi, 
I fixed all the problems the script works normally nickel! I am really sorry for the time I am making you lose. Try on your side and tell me if everything is fine.

(Warning I also modify the Config file not to put the old config file).
