### ISSUE TITLE
fbi job doesnt register as cop online

### ISSUE THREAD

**Issue by GrimReefer420** [ESX-FRANCE/esx_fbi_job#7]
is there a way to get the fbi to register as "cops online" for burglaries, selling drugs, etc?

**Comment by keketiger** [comment]
Hi @GrimReefer420 , it is totally possible to register fbi members as being online. If you wish I can help you to do this, you just need send me the link of each script for which there is need to add the fbi. As for example the drug, that the fbi can not harvest.

Hoping to have answered your main question.
Good day to you!

**Comment by keketiger** [comment]
Hi @GrimReefer420 , it is totally possible to register fbi members as being online. If you wish I can help you to do this, you just need send me the link of each script for which there is need to add the fbi. As for example the drug, that the fbi can not harvest.

Hoping to have answered your main question.
Good day to you!

**Comment by keketiger** [comment]
Hello, you have closed your request for help I imagine you have solved your problem.

**Comment by GrimReefer420** [comment]
Yes I figured it out. Only trouble I have now it's when I escort I can't
release the player.
